#
# Copyright 2020-2026 Lars Pastewka
#
# ### MIT license
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#
# Gwyddion OPD reader:
# https://sourceforge.net/p/gwyddion/code/HEAD/tree/trunk/gwyddion/modules/file/opdfile.c
#

from ..Exceptions import CorruptFile, FileFormatMismatch, UnsupportedFormatFeature
from .binary import BinaryArray, BinaryStructure, Validate
from .expr import C, Cond, F, Tup, V
from .Reader import (
    Check,
    CompoundLayout,
    DeclarativeReaderBase,
    For,
    ForEach,
    If,
    Let,
    SizedChunk,
    Skip,
    Switch,
)

# Each directory entry is a 16-byte name followed by type, length and
# attribute fields
_BLOCK_HEADER_SIZE = 24

_block_header = [
    ("name", "16s"),
    ("type", "h"),
    ("length", "l"),
    ("attribute", "H"),
]

# Data raster: dimensions and element size, followed by the raw data.
# The block name is captured from the enclosing directory entry so that
# it can name the channel.
_raster = CompoundLayout(
    [
        Let({"block_name": C.__parent__.item.name}),
        BinaryStructure(
            [
                ("nb_grid_pts_x", "H", Validate(V > 0, CorruptFile)),
                ("nb_grid_pts_y", "H", Validate(V > 0, CorruptFile)),
                (
                    "itemsize",
                    "H",
                    Validate(V.isin(1, 2, 4), UnsupportedFormatFeature),
                ),
            ],
            byte_order="<",
            name="header",
        ),
        BinaryArray(
            "data",
            # The data is stored with the x index first
            Tup(C.header.nb_grid_pts_x, C.header.nb_grid_pts_y),
            Cond(
                C.header.itemsize == 1,
                F.dtype("c"),
                Cond(
                    C.header.itemsize == 2, F.dtype("<i2"), F.dtype("<f4")
                ),
            ),
            # Flip the y direction (like other implementations of this
            # format)
            conversion_fun=F.flip(V, 1),
        ),
    ],
    name="raster",
)

_wavelengths = F.pluck(C.payloads, "wavelength")
_mults = F.pluck(C.payloads, "mult")
_aspects = F.pluck(C.payloads, "aspect")
_pixel_sizes = F.pluck(C.payloads, "pixel_size")

_mult = Cond(F.len(_mults) > 0, _mults[0], 1.0)
_aspect = Cond(F.len(_aspects) > 0, _aspects[0], 1.0)
_pixel_size = Cond(F.len(_pixel_sizes) > 0, _pixel_sizes[0], 1.0)

# Heuristic for undefined data points: points that are not finite or
# that exceed a data-type dependent maximum value (32766 for 16-bit
# integers, 1e38 for floats) are undefined
_undefined_mask = Cond(
    C.item.header.itemsize == 1,
    False,
    F.logical_not(
        F.isfinite(V)
        & (V < Cond(C.item.header.itemsize == 2, 32766, 1.0e38))
    ),
)


class OPDReader(DeclarativeReaderBase):
    _format = "opd"
    _mime_types = ["application/x-wyko-opd"]
    _file_extensions = ["opd"]

    _name = "Wyko OPD"
    _description = """
OPD files generated by the Vision software of Bruker Wyko white-light
interferometers.
"""

    # The 'Directory' block name follows a two-byte prelude
    _magic = [(2, b"Directory")]

    _file_layout = CompoundLayout(
        [
            Skip(2, comment="prelude"),
            BinaryStructure(
                [
                    ("name", "16s", Validate("Directory", FileFormatMismatch)),
                    ("type", "h"),
                    ("length", "l"),
                    ("attribute", "H"),
                ],
                byte_order="<",
                name="directory_header",
            ),
            Check(
                C.directory_header.length % _BLOCK_HEADER_SIZE == 0,
                CorruptFile,
                "Directory length is not a multiple of the block size.",
            ),
            For(
                C.directory_header.length // _BLOCK_HEADER_SIZE - 1,
                BinaryStructure(_block_header, byte_order="<"),
                name="directory",
            ),
            # The block payloads follow in directory order; each block
            # occupies exactly the length declared in the directory,
            # independent of how many bytes are actually interpreted.
            # Blocks with non-positive lengths have no payload.
            ForEach(
                C.directory,
                If(
                    C.item.length > 0,
                    SizedChunk(
                        C.item.length,
                        Switch(
                            C.item.name,
                            {
                                "RAW DATA": _raster,
                                "RAW_DATA": _raster,
                                "OPD": _raster,
                                "Raw": _raster,
                                "Wavelength": BinaryStructure(
                                    [("wavelength", "f")], byte_order="<"
                                ),
                                "Mult": BinaryStructure(
                                    [("mult", "H")], byte_order="<"
                                ),
                                "Aspect": BinaryStructure(
                                    [("aspect", "f")], byte_order="<"
                                ),
                                "Pixel_size": BinaryStructure(
                                    [("pixel_size", "f")], byte_order="<"
                                ),
                            },
                            default=Skip(),
                        ),
                        mode="skip-missing",
                    ),
                ),
                name="payloads",
            ),
            Check(
                F.len(_wavelengths) > 0,
                CorruptFile,
                "File does not contain a 'Wavelength' block; cannot "
                "determine the height scale.",
            ),
        ]
    )

    _channel_bindings = [
        {
            # One channel per data raster block
            "foreach": F.pluck(C.payloads, "raster"),
            "name": C.item.block_name,
            "dim": 2,
            "nb_grid_pts": Tup(
                C.item.header.nb_grid_pts_x, C.item.header.nb_grid_pts_y
            ),
            "physical_sizes": Tup(
                C.item.header.nb_grid_pts_x * _pixel_size,
                C.item.header.nb_grid_pts_y * _pixel_size * _aspect,
            ),
            # Heights are in nm, widths in mm
            "height_scale_factor": _wavelengths[0] / _mult * 1e-6,
            "uniform": True,
            "unit": "mm",
            "data": C.item.data,
            "mask": {"source": C.item.data, "rule": _undefined_mask},
        }
    ]
