#name: Test building wheels
#
#on:
#  push:
#    branches:
#      - '**'
#    tags:
#      - '**'
#  pull_request:
#    branches:
#      - '**'
#
#jobs:
#  build_wheels:
#    name: Build wheels on ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, macos-latest]
#      fail-fast: false
#
#    steps:
#    - uses: actions/checkout@v3
#      with:
#        fetch-depth: 0
#
#    - name: Install cibuildwheel
#      run: python3 -m pip install cibuildwheel==2.9.0
#
#    - name: Build wheels
#      run: |
#        if [[ "{{ runner.os }}" == "Linux" ]]; then
#          for image in manylinux2010 manylinux2014; do
#            CIBW_MANYLINUX_X86_64_IMAGE=$image python3 -m cibuildwheel --output-dir wheelhouse
#          done
#        else
#          python3 -m cibuildwheel --output-dir wheelhouse
#        fi
#      env:
#        CIBW_BEFORE_ALL_LINUX: yum install -y blas-devel lapack-devel
#        CIBW_BUILD_VERBOSITY: 1
#        CIBW_SKIP: cp27-* cp35-* cp36-* cp311-* pp* *musllinux*
#        CIBW_ARCHS_MACOS: "universal2"
#        CIBW_BEFORE_BUILD: "pip install oldest-supported-numpy"
#        CIBW_TEST_REQUIRES: "pytest"
#        CIBW_TEST_COMMAND: "pytest {project}/tests"
#        CIBW_TEST_SKIP: "*"
