name: Test build and install of source package

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Installing Python
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y \
          python3-dev \
          python3-pip \
          python3-venv \
          libxml2-dev \
          libxslt-dev \
          zlib1g-dev \
          libfftw3-dev \
          libopenblas-dev \
          meson
        python3 -m venv ../venv
        source ../venv/bin/activate
        pip install pip-tools
        pip-compile -q pyproject.toml
        pip install -r requirements.txt

    - name: Build package
      run: |
        source ../venv/bin/activate
        meson setup build
        cd build
        meson dist --formats gztar

    - name: Install package
      run: |
        pip install build/meson-dist/*.tar.gz
