name: Test code functionality

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: "0 2 * * 5"  
jobs:
  tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    strategy:
      matrix:
        mpi: ['yes', 'no']
        python-version: ['3.7', '3.8', '3.9', '3.10']
        mpi4py-version: [3.1.4]
        netcdf4-python-version: [1.6.1]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up python3 ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update -qy
        if [ "${{ matrix.mpi }}" == "yes" ]; then
          sudo apt-get install -y \
            libfftw3-dev \
            libopenblas-dev \
            openmpi-bin \
            libopenmpi-dev \
            libfftw3-mpi-dev \
            libhdf5-mpi-dev \
            libpnetcdf-dev \
            libnetcdf-pnetcdf-dev
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip pip-tools
          # Compute mpi4py and muFFT versions
          pip-compile pyproject.toml
          MUFFT_VERSION=$(grep mufft requirements.txt)
          # Install mpi4py
          echo "Installing mpi4py==${{ matrix.mpi4py-version }}"
          CC=mpicc python3 -m pip install -v \
            --no-binary mpi4py \
            mpi4py==${{ matrix.mpi4py-version }}
          # Install netCDF4 with MPI support
          echo "Installing netCD4==${{ matrix.netcdf4-python-version }}"
          CC=mpicc NETCDF4_DIR=/usr/lib/x86_64-linux-gnu/netcdf/pnetcdf python3 -m pip install -v \
            --no-binary mpi4py --no-binary netCDF4 \
            netCDF4==${{ matrix.netcdf4-python-version }}
          # Manually install muFFT with MPI enabled
          echo "Installing ${MUFFT_VERSION}"
          WD=$(pwd)
          cd ..
          pip download ${MUFFT_VERSION}
          tar -zvxf muFFT-*.tar.gz
          cd muFFT-*/
          python3 setup.py install --mpi --force
          cd ${WD}
        else
          sudo apt-get install -y \
            libfftw3-dev \
            libopenblas-dev 
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip pip-tools
        fi
        python3 -m pip install build
        python3 -m pip list

    - name: Install extension module
      run: |
        source venv/bin/activate
        python3 -m pip install .[test]

    - name: Test with pytest
      run: |
        source venv/bin/activate
        python3 .check_netcdf_capabilities.py ${{ matrix.mpi }}
        python3 .check_mufft_capabilities.py ${{ matrix.mpi }}
        if [ "${{ matrix.mpi }}" == "yes" ]; then python3 run-tests.py --no-build --verbose --full-trace; else python3 -m pytest --verbose --full-trace -s; fi
